server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:practice
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:/db/migration
#    baseline-version: 1
logging:
  level:
    org.springframework:
      messaging: trace
      web:
        socket: trace
